/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: ed4f0098528906f04aeee09dd27ea9ee)
// Runtime types generated with workerd@1.20250617.0 2024-11-12 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		ENV: "prod" | "dev-test" | "local-demo";
		AI_MODEL_NAME: "google-ai-studio/gemini-2.0-flash" | "llama3";
		FORCE_USE_AI_BASE_URL: "true";
		AI_BASE_URL: string;
		DB: D1Database;
        SECRET_TELEGRAM_API_TOKEN: string;
        TELEGRAM_ADMIN_ID: string;
        ACCOUNT_ID: string;
        AI_GATEWAY_ID: string;
        CF_AIG_TOKEN: string;
        AI_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {
	[x: string]: any;
}