// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_TELEGRAM_API_TOKEN: string;
	GEMINI_API_KEY: string;
	GATEWAY_NAME: string;
	account_id: string;
	DB: D1Database;
	DB_ID?: string;
}
